### ISSUE TITLE
How Can i use this them in my Website

### ISSUE THREAD

**Issue by Rebaiahmed** [Brobin/hacker-bootstrap#2]
Hello how can I use this theme in my website ?

**Comment by Brobin** [comment]
You can download the file from the repo (https://github.com/Brobin/hacker-bootstrap/blob/gh-pages/css/hacker.css)

Or reference it like any other css file

```html
<link rel="stylesheet" type="text/css" href="https://brobin.github.io/hacker-bootstrap/css/hacker.css"/>
```
